Report screen UI design
teamlead-rdl/AirQualityMonitoringSystem pull request #58
Opened 2022-06-17 06:36 UTC by Prajwalkodmannu

2022-06-17 10:31 UTC, teamlead-rdl requested changes

2022-06-17 10:31 UTC, teamlead-rdl commented on src/components/reportSectionComponents/AqmiLog.js
> +import Box from '@mui/material/Box';
Please import the object using Destructuring method

2022-06-17 10:31 UTC, teamlead-rdl commented on src/components/reportSectionComponents/BumpTest.js
> +import InputLabel from '@mui/material/InputLabel';
Use Destructuring method

2022-06-17 10:31 UTC, teamlead-rdl commented on src/components/reportSectionComponents/IndividualReportForm.js
> +                            {/* <MenuItem value={10}>Ten</MenuItem>
remove the commented code

2022-06-17 10:31 UTC, teamlead-rdl commented on src/components/reportSectionComponents/ManagementReportTab.js
> +    const { children, value, index, ...other } = props;
What does "Other" object stand for ? Maintain the naming convention in the code

2022-06-17 10:31 UTC, teamlead-rdl commented on src/components/reportSectionComponents/ManagementReportTab.js
> +                                    id="demo-simple-select"
Remove such ID which is been directly derived from Example code

2022-06-17 10:31 UTC, teamlead-rdl commented on src/components/reportSectionComponents/ManagementReportTab.js
> +                                    id="demo-simple-select"
Remove such id from the code

2022-06-17 10:31 UTC, teamlead-rdl commented on src/components/reportSectionComponents/ManagementReportTab.js
> +                                    id="demo-simple-select"
Remove ID

2022-06-17 10:31 UTC, teamlead-rdl commented on src/config/roleConfig.js
> +  admin: ['Dashboard', 'Location', 'UserManagement', 'Vendor', 'ReportAqms', 'ChangePassword', 'AddDevice', 'DeviceLocation'],
1. Please take a confirmation from the Client on which Roles do they need this Tab. 
2. Please do confirm on the download access from the client for these role and Access

2022-06-17 10:50 UTC, Ranjith-K-07 requested changes

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/navbarComponent/SidebarItems.jsx
> +import SummarizeIcon from '@mui/icons-material/Summarize';
Remove this import and put the icon 'SummarizeIcon' in above import(in line number 4- inside flower braces).

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/Alarm.js
> +import Stack from '@mui/material/Stack';
Import all the MUI component in single line rather than individual import.

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/Alarm.js
> +
remove extra line

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/Alarm.js
> +    const [age, setAge] = React.useState('');
Do not use 'useState' like this way. Initially import the hook globally then use it.

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/Alarm.js
> +                    label="From date"
Capitalise the letter 'd' in 'From date'

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/Alarm.js
> +                            label="Age"
Make sure that you are using the correct label value while copying. 
Change Age into AQMI/AQMO

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/AqmiLog.js
> +import Divider from '@mui/material/Divider';
Import all components in one line

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/BumpTest.js
> +import Stack from '@mui/material/Stack';
import all the component in one line

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/BumpTest.js
> +
remove empty line

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/BumpTest.js
> +                            <MenuItem value={20}>Bump Test Result</MenuItem> */}
remove unwanted code if it is not required in the future use.

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/BumpTest.js
> +
remove empty line

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/BumpTest.js
> +
remove empty line

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/FirmwareVersion.js
> +import Divider from '@mui/material/Divider';
import all components in one line

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/FirmwareVersion.js
> +
remove empty line

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/FirmwareVersion.js
> +                            label="Age"
change the label from 'Age' to 'Type'

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/IndividualReportForm.js
> +import TablePagination from '@mui/material/TablePagination';
import all components in one line

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/FirmwareVersion.js
> +    const [age, setAge] = React.useState('');
import useState first, then use it

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/IndividualReportForm.js
> +    const [age, setAge] = React.useState('');
import useState globally then use it

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/IndividualReportForm.js
> +                            label="Age"
change label name

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/IndividualReportForm.js
> +                            <MenuItem value={20}>Twenty</MenuItem>
remove commented code if it is not required

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/IndividualReportForm.js
> +                                            <TableCell sx={{ width: 20 }} >{val}</TableCell>
remove empty lines

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/ManagementReportTab.js
> +import Grid from '@mui/material/Grid';
import all components in one line

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/ManagementReportTab.js
> +    children: PropTypes.node,
is this code block required? And are you familiar with this code block?

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/ManagementReportTab.js
> +    const [age, setAge] = React.useState('');
import useState globally

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/ManagementReportTab.js
> +                                    label="Age"
change label name

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/ManagementReportTab.js
> +                                    label="Age"
change label name

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/ManagementReportTab.js
> +                                    label="Age"
change label name

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/ManagementReportTab.js
> +                                    label="Age"
change label name

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/ManagementReportTab.js
> +                                    label="Age"
change label name

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/SensorLog.js
> +import Divider from '@mui/material/Divider';
import components in one line

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/SensorLog.js
> +    const [age, setAge] = React.useState('');
import useState globally

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/SensorLog.js
> +                    label="From date"
Capitalise 'd' in date

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/ServerUtilization.js
> +import Stack from '@mui/material/Stack';
import in single line

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/ServerUtilization.js
> +
remove empty line

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/SitesReportForm.js
> +import Button from '@mui/material/Button';
import in single line

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/SitesReportForm.js
> +    const [age, setAge] = React.useState('');
import useState globally

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/SitesReportForm.js
> +                            label="Age"
change label name

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/SitesReportForm.js
> +                            <MenuItem value={20}>Branch</MenuItem>
remove comments if it is not required

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/config/roleConfig.js
> +  admin: ['Dashboard', 'Location', 'UserManagement', 'Vendor', 'ReportAqms', 'ChangePassword', 'AddDevice', 'DeviceLocation'],
Change ReportAqms to 'Report'

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/config/roleConfig.js
> +  ReportAqms: {
Change ReportAqms to 'Report'

2022-06-17 10:50 UTC, Ranjith-K-07 commented on src/App.js
> +              <Route path="ReportAqms/*" element={<ManagementReportTab />} />
Change ReportAqms to 'Report'

2022-06-17 10:52 UTC, Ranjith-K-07 commented on src/components/reportSectionComponents/AqmiLog.js
> +
Remove extra line

2022-06-20 10:14 UTC, teamlead-rdl approved these changes

2022-06-20 10:15 UTC, merged