Static dashboard
teamlead-rdl/AirQualityMonitoringSystem pull request #69
Opened 2022-08-04 07:31 UTC by abhishekRdl

i have Merged changes and ran eslint for the pages that i have worked.

2022-08-04 08:45 UTC, teamlead-rdl requested changes

2022-08-04 08:45 UTC, teamlead-rdl commented on src/components/Device/deviceConfiguration/subcomponent/ConfigSetupModalComponent.js
> +  /* eslint-disable-next-line */
Eslint disabling do it in one line at the header if the lint is of similar way

2022-08-04 08:45 UTC, teamlead-rdl commented on src/components/Device/deviceConfiguration/subcomponent/ConfigSetupModalComponent.js
> +              autoComplete="new-password"
Why is it marked as New-password? Is it a requirement?

2022-08-04 08:45 UTC, teamlead-rdl commented on src/components/Device/deviceConfiguration/subcomponent/ConfigSetupModalComponent.js
> +              autoComplete="new-password"
"New-password" is it in requirement?

2022-08-04 08:45 UTC, teamlead-rdl commented on src/components/Device/subComponent/BumpTestComponentModal.js
>              avg = tot / dataList;
Please correct the spell of tot to something meaningful

2022-08-04 08:58 UTC, abhishekRdl commented on src/components/Device/deviceConfiguration/subcomponent/ConfigSetupModalComponent.js
> +              autoComplete="new-password"
Hi sir, AutoComplete was  not working in edge, when i googled it , it came we need to add new-password

2022-08-05 06:29 UTC, teamlead-rdl commented on src/components/Device/subComponent/BumpTestComponentModal.js
>              avg = tot / dataList;
@abhishekRdl , please push theis change

2022-08-08 04:27 UTC, abhishekRdl commented on src/components/Device/subComponent/BumpTestComponentModal.js
>              avg = tot / dataList;
I have done changes as told by you

2022-08-08 04:27 UTC, closed without merging